Traceback (most recent call last):
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from empylib.fresnel import interface

theta = np.linspace(0,90,100) # √Ångulo de incidencia
# Reflectividad en una interface
Rp = lambda n1,n2 : interface(theta,n1,n2)[0] # TM
Rs = lambda n1,n2 : interface(theta,n1,n2)[4] # TE

# preparamos el ploteo
def plot_R_interface(n1,n2):
    fig, ax = plt.subplots()
    fig.set_size_inches(9, 6)
    plt.rcParams['font.size'] = '18'
    ax.plot(theta,Rp(n1,n2), label='$R_\mathrm{TM}$', color='red')
    ax.plot(theta,Rs(n1,n2), label='$R_\mathrm{TE}$',color='blue')
    ax.set_xlim([0,90])
    ax.set_ylim([0,1.0])
    ax.set_xlabel('√Ångulo de incidencia (¬∞)')
    ax.set_ylabel('Reflectividad')
    ax.legend(frameon=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/tmp/ipykernel_663/3392137778.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mfrom[0m [0mempylib[0m[0;34m.[0m[0mfresnel[0m [0;32mimport[0m [0minterface[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mtheta[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlinspace[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m90[0m[0;34m,[0m[0;36m100[0m[0;34m)[0m [0;31m# √Ångulo de incidencia[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'empylib'
ModuleNotFoundError: No module named 'empylib'

