Traceback (most recent call last):
  File "/home/panxopanza/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/panxopanza/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/panxopanza/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/panxopanza/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/panxopanza/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/panxopanza/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/panxopanza/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/panxopanza/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
lam_vis = np.linspace(0.35,0.75,1000) # espectro de longitudes de onda en el visible
Tvis_lam = np.interp(lam_vis,lam,T)  # transmitancia en el visible

# Transmitancia lum√≠nica
Tlum = np.trapz(rf.yCIE_lum(lam)*T,lam)/np.trapz(rf.yCIE_lum(lam),lam)*100
print('Tranmitancia lum√≠nica: %.1f%%' % Tvis)

# Ganancia solar
Tsolar = np.trapz(rf.AM15(lam)*T,lam)/np.trapz(rf.AM15(lam),lam)*100
print('Ganancia solar: %.1f%%' % Tsolar)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 6[0m
[1;32m      4[0m [38;5;66;03m# Transmitancia lum√≠nica[39;00m
[1;32m      5[0m Tlum [38;5;241m=[39m np[38;5;241m.[39mtrapz(rf[38;5;241m.[39myCIE_lum(lam)[38;5;241m*[39mT,lam)[38;5;241m/[39mnp[38;5;241m.[39mtrapz(rf[38;5;241m.[39myCIE_lum(lam),lam)[38;5;241m*[39m[38;5;241m100[39m
[0;32m----> 6[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mTranmitancia lum√≠nica: [39m[38;5;132;01m%.1f[39;00m[38;5;132;01m%%[39;00m[38;5;124m'[39m [38;5;241m%[39m [43mTvis[49m)
[1;32m      8[0m [38;5;66;03m# Ganancia solar[39;00m
[1;32m      9[0m Tsolar [38;5;241m=[39m np[38;5;241m.[39mtrapz(rf[38;5;241m.[39mAM15(lam)[38;5;241m*[39mT,lam)[38;5;241m/[39mnp[38;5;241m.[39mtrapz(rf[38;5;241m.[39mAM15(lam),lam)[38;5;241m*[39m[38;5;241m100[39m

[0;31mNameError[0m: name 'Tvis' is not defined
NameError: name 'Tvis' is not defined

